name: mybinder
channels:
  - default
dependencies:
  - python=3.8
  - pandas
  - dask
  - numpy
  - networkx
  - matplotlib
  - line_profiler
  - numba
  - bokeh
  - statsmodels
  - pip
  pip:
    - linearmodels
    - yfinance

